services:
  - type: web
    name: naukri-automation
    env: python
    buildCommand: "pip install -r requirements.txt && playwright install chromium"
    startCommand: "gunicorn app:app"
    plan: free
    envVars:
      - key: NAUKRI_EMAIL
        sync: false
      - key: NAUKRI_PASSWORD
        sync: false
      - key: HEADLESS
        value: "true"