services:
  - type: web
    name: naukri-automation
    env: docker
    plan: free
    envVars:
      - key: NAUKRI_EMAIL
        sync: false
      - key: NAUKRI_PASSWORD
        sync: false
      - key: HEADLESS
        value: "true"