site:
  name: "naukri"
  url: "https://www.naukri.com/mnjuser/profile"

schedule:
  enabled: true
  mode: "daily"         # daily | cron
  time_ist: "05:00"     # HH:MM 24h IST for daily
  cron: "0 5 * * *"     # if mode=cron (IST)

resume:
  path: "resumes/latest_resume.pdf"

behavior:
  retry_on_fail: true
  max_retries: 2
  wait_after_login_sec: 4
  wait_after_upload_sec: 5

observability:
  screenshots_on_error: true
  trace_on_error: false

timezone: "Asia/Kolkata"
user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"